### ISSUE TITLE
Add new Stage in nested library

### ISSUE THREAD

**Issue by Quaiks** [griddynamics/mpl#20]
Hello!! First of all... I love this project! I am migrating every pipeline of our organization. I've been looking for this kind of modular/composable/awesome Jenkins Shared library organization for a long time. Congratz!!

My problem is that I am trying to create a new pipeline in a nested library with a new stage like this.

```

stage('StaticCodeAnalysis') {
    when { expression { MPLModuleEnabled() } }
    steps {
        MPLModule()
    }
}
```

I am getting the following log message in Jenkins `Stage "StaticCodeAnalysis" skipped due to when conditional`

How can I "register" a new stage? I don't get how `MPLModuleEnabled` works.

Thans in advance!

**Comment by Quaiks** [comment]
Well this was easy...
```
MPLPipelineConfig(body, [
            agent_label: '',
            modules    : [
                    Checkout          : [:],
                    Build             : [:],
                    Deploy            : [:],
                    Test              : [:],
                    StaticCodeAnalysis: [:]
            ]
])
```

I just had to add the stage/module in the initial config.

**Comment by sparshev** [comment]
Hi @Quaiks, yeah that's because you used `when { expression { MPLModuleEnabled() } }` - and MPLModuleEnabled() is only true when MPL.config.modules[module_name] is not null.
