### ISSUE TITLE
MPLManager.instance.<any api> is throwing null Pointer

### ISSUE THREAD

**Issue by amiteshsharma** [griddynamics/mpl#35]
Hi Sergei, 

I checked out the mpl framework hosted in this repo.
However was not able to run below instructions.

@Library('mpl') _
MPLPipeline {}

Error:
java.lang.NullPointerException
at com.cloudbees.groovy.cps.impl.CpsCallableInvocation.invoke(CpsCallableInvocation.java:51)

It seems invoking @Singleton Mgr class is throwing exception.

Env:
Using: Jenkins 2.176.2

Note: Similar issue reported in https://stackoverflow.com/questions/52609080/jenkins-scripted-pipeline-singleton-null-pointer-exception

Can you please suggest the fix.

Thanks and Regards,
Amitesh

**Comment by sparshev** [comment]
Hi @amiteshsharma ,

That's weird - I tried 2.176.2 not so long time ago but saw no such issues. Could you please list the plugins/versions you using on your jenkins?

Thank you.

**Comment by amiteshsharma** [comment]
Hi Sergei,

Thanks a lot for your prompt response.

Yes, i tried with other examples shared in mpl.wiki, as well, and got same issue.
However, right now I have quite a lot of plugins which are not being used.
As per your confirmation, if it's working with latest version, i'll cross check the mpl  behavior again with only needful plugins, and removing uncessary ones.

In case i face the issue again, will surely get back to you.

Thanks and Best Regards,
Amitesh

**Comment by sparshev** [comment]
Ok, I will close it for now - but please feel free to reopen when you will find some additional information.
