### ISSUE TITLE
MplConfig singleton

### ISSUE THREAD

**Issue by marcelaraujo** [griddynamics/mpl#41]
Hi,

Why does every module create a new MplConfig instance instead of provides unique instance?

In some modules I need update config and reflecting on the next modules.

Tks

**Comment by sparshev** [comment]
Hi @marcelaraujo,

The reason why MPL was born - is to fight the "Configuration hell" problem - so the whole architecture of MPL is trying to make sure there will be no "global" configuration. The modules can control what's inside their CFG and pass this CFG to the children modules (using MPLModule('name', CFG)) - but can't affect CFG for the parent modules/pipeline.

You can get some additional info in #10 and #8 (where we working on solution to provide the return interface to control the configuration content properly).

Thank you

**Comment by sparshev** [comment]
Almost a month no response - so I think I can close it.
