### ISSUE TITLE
jenkins ruby-runtime plugin

### ISSUE THREAD

**Issue by inzagod** [griddynamics/mpl#50]
hi,

after upgrade openshift platform in 3.11.153 version, i want to upgrade my jenkins project.
i built my new custom image of jenkins-2-rhel7 in 3.11.153 version like i did in 3.9.60.
in 3.9.60, plugin ruby-runtime works fine.
here, when i tried to start my docker image by a docker run i received these errors :

SEVERE: Failed Inspecting plugin /var/lib/jenkins/plugins/ruby-runtime.jpiSEVERE: Failed Inspecting plugin /var/lib/jenkins/plugins/ruby-runtime.jpijava.io.IOException: Failed to expand /var/lib/jenkins/plugins/ruby-runtime.jpi at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:478) at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:174) at hudson.PluginManager$1$3$1.run(PluginManager.java:431) at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169) at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296) at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095) at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214) at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)Caused by: Error while expanding /var/lib/jenkins/plugins/ruby-runtime.jpijava.util.zip.ZipException: archive is not a ZIP archive at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:190) at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:132) at hudson.ClassicPluginStrategy.unzipExceptClasses(ClassicPluginStrategy.java:550) at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:475) ... 10 moreCaused by: java.util.zip.ZipException: archive is not a ZIP archive at org.apache.tools.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:771) at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:707) at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:452) at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:214) at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:168) ... 13 more

i tried so to start the image directly in openshift and the error is the same.

in openshift, i set these environment variables :

JENKINS_JAVA_OVERRIDES ==> -Dhudson.model.UpdateCenter.never=true -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85

i saw in several post or report issues that i can add this variable : -Dhudson.ClassicPluginStrategy.noBytecodeTransformer=true

 for me it not solved my problem.
 someone can help me  ?

 thanks a lot
ludo

**Comment by sparshev** [comment]
Hi @inzagod ,

Could you please describe how this issue is related to MPL? Maybe it's more about the plugin you using - you can try to contact the developers of ruby-runtime plugin.

What I can see in the exception - that the plugin package (jpi) is corrupted, check the md5/sha checksum and make sure it's the right one.

Thank you.

**Comment by inzagod** [comment]
hi @sparshev,

thanks a lot for your help

in fact i downloaded the hpi file @ : https://updates.jenkins.io/download/plugins/ruby-runtime/
but there is some security in my society and the files i downloaded was truncated (7.5mo between 18mo)
i received no security warn so i don't think that there is a problem with this file.
so annoying !
i downloaded it with a connection share with my phone and the file is ok (18mo).

my problem is solved !

great !

thanks a lot

**Comment by sparshev** [comment]
Anyway the issue is not related to MPL - so please make sure you will create the issue in the proper place next time.

**Comment by inzagod** [comment]
ok sorry for the mistake.
when i created the issue, i don't know exactly where is the issue

thanks
