### ISSUE TITLE
Remove example module path

### ISSUE THREAD

**Issue by marcelaraujo** [griddynamics/mpl#61]
Hi, is it possible to remove this default path and add it into MPLPipeline using MPLModulesPath?

https://github.com/griddynamics/mpl/blob/4ca95b9d157c39ebaea063691bb247d390846aff/src/com/griddynamics/devops/mpl/MPLManager.groovy#L50

**Comment by sparshev** [comment]
Hi @marcelaraujo 

Need to think about it - probably it's not a good thing, that this path is set by default without a way to remove it, but adding new paths right now is located in MPLInit for the shared libraries. So let me check the possible ways.

**Comment by marcelaraujo** [comment]
I think you could use `MPLModulesPath` inside `MPLPipeline.groovy` and fix ours both needs.

**Comment by sparshev** [comment]
@marcelaraujo , there is multiple ways - but when you making some changes that breaking the backward-compatibility - you need to be very cautious.

Could you please describe - what the particular issue you have with this default path?

**Comment by sparshev** [comment]
@marcelaraujo - I see no updates in this issue, could you please check my last question?

**Comment by sparshev** [comment]
No answer for 2w, closing the issue.
