### ISSUE TITLE
How to Parameterized Build like origin pipeline keyword [parameters]

### ISSUE THREAD

**Issue by Cheava** [griddynamics/mpl#63]
This project is great, and I want to build our company ci architure based on it.
Because of multi environment and sub-project in our company, so I'm wondering how to parameterized build  as title said. 
Thank you.

**Comment by sparshev** [comment]
Hi @Cheava ,

MPL allows to configure the pipeline through `MPLPipelineConfig` and further altering/adjusting this configs through `CFG` passed to the modules and `OUT` from the modules. To use parameters of the build itself - you can use the common jenkins global variables allowed in the same [MPLPipelineConfig](/griddynamics/mpl/blob/master/vars/MPLPipelineConfig.groovy#L48)

For example, when you creating the pipeline job - you can set the job build parameter with name `BUILD_PARAM` and use it in the Jenkinsfile / Pipeline Script:
```groovy
...
MPLPipeline {
    my_param = params.BUILD_PARAM
    modules.Build.my_env = env.USER
}
```

Then in the module you can use this global `my_param` as `CFG.my_param` just like the same in Build module(s) the `CFG.my_env`.

Of course you can use the same env/params directly in your NestedPipeline during providing defaults/mandatory configs to `MPLPipelineConfig`.

**Comment by sparshev** [comment]
@Cheava , I see no updates for almost a week - so I think the question was answered. Please reopen it if that's wrong.

**Comment by Cheava** [comment]
The question has been solved.  Thank you~
