### ISSUE TITLE
[Q] Passing variables between stages

### ISSUE THREAD

**Issue by sparshev** [griddynamics/mpl#69]
Hi, I started using the libraries, But If I want some variables from one stage to another stage How can it be done?

_Originally posted by @yamsivakumarreddy in https://github.com/griddynamics/mpl/issues/58#issuecomment-617623927_

**Comment by sparshev** [comment]
@yamsivakumarreddy, please don't post the offtopic questions. Answer on your question is simple - MPLModule supports OUT interface, please check [README doc here](/griddynamics/mpl/blob/master/README.md#mplmodule-return) and this question: #66

**Comment by yamsivakumarreddy** [comment]
Hi @sparshev I am getting the below error when I use OUT in checkout.groovy

groovy.lang.MissingPropertyException: No such property: OUT for class: groovy.lang.Binding

-->checkout.groovy
  def version = MPLModule('Default Checkout').'artifact.version'
  echo "${version}"
  OUT.'artifact_info.artifact.version' = version
--> defaultcheckout.groovy
  gitInfo = checkout scm
  OUT.'artifact.version' = 1
--> pipeline
 stage( 'Checkout' ) {
        when { expression { MPLModuleEnabled() } }
        steps {
          echo "in checkout step"
          MPLPipelineConfigMerge(MPLModule('Checkout').artifact_info)
        }
      }

**Comment by sparshev** [comment]
What the version of MPL you're using? OUT was added to master branch in the PR #46

**Comment by sparshev** [comment]
Hopefully the question was answered.

**Comment by yamsivakumarreddy** [comment]
@sparshev thanks for your patience, it worked very well :) I upgraded from jenkins shared libraries to MPL.
