### ISSUE TITLE
Demo video links in wiki broken?

### ISSUE THREAD

**Issue by jfischer1** [griddynamics/mpl#82]
When browsing the MPL wiki, the links at main page, section 'Overview and Demo Videos', seem to be broken. Youtube displays error message "video unavailable - uploader closed account". Are there any alternative locations to view these videos?

**Comment by sparshev** [comment]
Hi @jfischer1 

Sorry about that, will check with GD what's happening and come back shortly.

Thank you

**Comment by sparshev** [comment]
Yeah, it's not so easy to restore the original videos... Will give some time to the IT guys and if there will be no way to do that, I will re-upload them if GD will allow to do that.

**Comment by sparshev** [comment]
Unfortunately the original videos was lost, so figuring out how to reupload them.

**Comment by sparshev** [comment]
Hi @jfischer1 , finally we completed the reuploading process and now the videos are available on [the separated MPL channel](https://www.youtube.com/channel/UClq6XV80D1DVscGvCAk70cg/):

* [Introduction](https://youtu.be/02zCNJ20AC0)
* [Overview](https://youtu.be/CXghkwmsoXY)
* [Demo of the MPL Build](https://youtu.be/knXX18E-W_s)
* [Demo of the Nested Library](https://youtu.be/D72vnIBxQYE)
* [Demo of the Petclinic Pipeline](https://youtu.be/Gq8RYlZjds0)

Will change the repo, wiki and articles links asap.

**Comment by jfischer1** [comment]
Hi @sparshev, thank you for taking care of this :)

**Comment by sparshev** [comment]
Ok, fixed in README & Wiki, last one - is https://blog.griddynamics.com/developing-a-modular-pipeline-library-to-improve-devops-collaboration/ - on GD

**Comment by sparshev** [comment]
The GD article was fixed, so we're good now)
