### ISSUE TITLE
mpl-nested example tests depend on mpl 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by maxime-michel** [griddynamics/mpl#86]
But I'm not sure in which repository to get the following dependency?

        <dependency>
            <groupId>com.griddynamics.devops</groupId>
            <artifactId>mpl</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>test</scope>
        </dependency>

While we're on the topic of mpl-nested tests, the TODO section of mpl-nested.md still lists 'Tests using MPL testing framework', which gives the impression to somebody who clones the repository for the first time that the tests that are available when the repository is cloned are not up-to-date. But I guess they are and that line was simply left there when the tests were commited in `519fc6b3`, right?

**Comment by sparshev** [comment]
Yeah, that's right - so you need to have the mpl 1.0.0-SNAPSHOT artifact (which contains the required testing framework) in order to run the nested lib tests.

About the TODO section in the examples - yep, you right, probably I forgot to remove it. Will remove it from the md file.

**Comment by maxime-michel** [comment]
> Will remove it from the md file.

Thanks, that clears things up to a complete newcomer like me.

> so you need to have the mpl 1.0.0-SNAPSHOT artifact

But where can I get it? Does the CircleCI build push it somewhere? I would rather avoid having to clone and deploy it to my local repository myself if possible. That's fine on a local machine, but eventually I will want the MPL tests for my nested library to run on our CI.

**Comment by sparshev** [comment]
Yeah, so how I saw it - when the organization forks MPL (or uses local) - it usually has nexus/artifactory and can build and deploy MPL to the maven artifact storage. For example in the real-example there is described how to setup nexus3 and go through mpl build & nested lib build.

Unfortunately you see - it's still snapshot, there is no 1.0.0 release and it will be incorrect to publish snapshot like that in the central, so no other way I see for now, unfortunately.

**Comment by maxime-michel** [comment]
Alright, thank you, I can deal with that if that's the only way for now.
