### ISSUE TITLE
Any way to introduce / reorder stages?

### ISSUE THREAD

**Issue by lprimak** [griddynamics/mpl#91]
My current pipelines involve different order of stages, for example, tests go before the deploy.
In MPL, it looks like stage order is hardcoded the opposite way. Any way to customize the order?
What about parallel steps? Can that be supported somehow?

See https://github.com/flowlogix/jenkins/blob/master/IntegrationTests.groovy for a simple example of
non-MPL-compliant stage naming and order

Thanks!

**Comment by sparshev** [comment]
Hi @lprimak, of course you can change the pipeline and create your own custom one: https://github.com/griddynamics/mpl#custom-declarative-pipeline-with-mixed-steps or https://github.com/griddynamics/mpl#using-nested-library-based-on-mpl - just copy the MPLPipeline.groovy to another file (like `MyCustomPipeline.groovy`), modify it as you want and use it. 

`MPLPipeline` is just an example and basic pipeline for simple projects. Probably the examples could help you to find your way: https://github.com/griddynamics/mpl/wiki#examples
* mpl-nested contains `vars/NestedPipeline.groovy`
* real-demo contains `example-cicd/vars/ExampleProjectPipeline.groovy`

**Comment by lprimak** [comment]
Perfect thanks
